// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxo8ZY5vKc95JcV_sRvYrXO54OTMjyYZk',
    appId: '1:629904567960:web:9bfc61d0c29c51bc55aaed',
    messagingSenderId: '629904567960',
    projectId: 'dalily-app-39b2c',
    authDomain: 'dalily-app-39b2c.firebaseapp.com',
    storageBucket: 'dalily-app-39b2c.firebasestorage.app',
    measurementId: 'G-SFZLXE6CBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj22ERCIkZjj3kRHMHC7pBhceQplsOks4',
    appId: '1:629904567960:android:c331f5348bf2354555aaed',
    messagingSenderId: '629904567960',
    projectId: 'dalily-app-39b2c',
    storageBucket: 'dalily-app-39b2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9wXXdaUD6h4qGMxtRoKPevMxKxrEJ_Zg',
    appId: '1:629904567960:ios:f73497683978156655aaed',
    messagingSenderId: '629904567960',
    projectId: 'dalily-app-39b2c',
    storageBucket: 'dalily-app-39b2c.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9wXXdaUD6h4qGMxtRoKPevMxKxrEJ_Zg',
    appId: '1:629904567960:ios:f73497683978156655aaed',
    messagingSenderId: '629904567960',
    projectId: 'dalily-app-39b2c',
    storageBucket: 'dalily-app-39b2c.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxo8ZY5vKc95JcV_sRvYrXO54OTMjyYZk',
    appId: '1:629904567960:web:9b865e59b5b763f755aaed',
    messagingSenderId: '629904567960',
    projectId: 'dalily-app-39b2c',
    authDomain: 'dalily-app-39b2c.firebaseapp.com',
    storageBucket: 'dalily-app-39b2c.firebasestorage.app',
    measurementId: 'G-LKB7SGVCWZ',
  );
}
